name: RBS collection

on:
  schedule:
    - cron: '00 8 * * MON'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/create-github-app-token@v2
      id: app-token
      with:
        app-id: ${{ vars.RBS_COLLECTION_UPDATER_APP_ID }}
        private-key: ${{ secrets.RBS_COLLECTION_UPDATER_PRIVATE_KEY }}
    - uses: actions/checkout@v6
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3
        bundler-cache: true
    - name: Update rbs collection
      run: bundle exec rbs collection update
    - name: Create a pull request
      uses: peter-evans/create-pull-request@v8
      with:
        add-paths: rbs_collection.lock.yaml
        commit-message: 'rbs: Update RBS collection'
        branch: bot/rbs-collection
        title: 'rbs: Update RBS collection'
        token: ${{ steps.app-token.outputs.token }}
